### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Startx04** [sugarcrm/SugarCE-Add-ons#50]
I have issues installing the module. 
- SugarCRM is Version 6.5.20 (Build 1001)
- AjaxUI turned off

When i upload the zip file in the module loader i get following message:
ZIP Error(0): Status(0): Arhive(upload://OpenQuotesAndContracts-fc493ea6263939106f9b0d7f872da842560d1358.zip): Directory(/usr/www/users/***/***/cache/upgrades/temp/kmDGrd)

And thats it. It does not open the install routine or anything else. Folder permission is on 775. Strange is also that the folder appears empty when accessing via ftp.

Any idea why that happens?

**Comment by Startx04** [comment]
Sorry, was on the wrong tab when creating the issue ^^

**Comment by beyondsilkyway** [comment]
linux] chmod -R 775 cache custom data modules
many error solved by this command.
ex) white page.

SugarCRM scheduler crontab setting off.
SugarCRM upgrading error solved by this.
linux ] crontab -e

 *    *    *    *    *     cd /sugarcrm; php -f cron.php > /dev/null 2>&1
