### ISSUE TITLE
WORST IDEA EVER

### ISSUE THREAD

**Issue by cmcintosh** [sugarcrm/SugarCE-Add-ons#79]
so you went from a solution that people could search to this?

**Comment by mikhailkozlov** [comment]
Most browsers have search feature nowadays. Since all content is on page you can simply use command/control+F to search. Github also has search feature right at the top of the page.

**Comment by cmcintosh** [comment]
Except that you dont have all of the projects listed here. Again horrible use case

**Comment by mikhailkozlov** [comment]
Chris, contributions are open to everyone. If you see a missing package or project, feel free to add it back.

**Comment by cmcintosh** [comment]
Explain how one would do that you took down the site where it was located, http://www.sugarforge.org/projects/sugar2drupal/ ? Please tell me how to find it.

**Comment by mikhailkozlov** [comment]
About 2 years ago we asked developers if they would like us to transfer their project listings to new directory. If someone chose not to list something, there is nothing we can do. With regard to that module it looks like OSSCube stopped developing it. Link to Drupal website returns 404. Even https://www.drupal.org/project/drupaltosugar has last release that is more than 2 years old. 

If you would like to  list a package, here is how to do it https://github.com/sugarcrm/SugarCE-Add-ons/blob/master/CONTRIBUTING.md
