### ISSUE TITLE
Please Re add

### ISSUE THREAD

**Issue by cmcintosh** [sugarcrm/SugarCE-Add-ons#80]
http://www.sugarforge.org/projects/sugar2drupal/ and provide links to the source.

**Comment by mikhailkozlov** [comment]
@cmcintosh free to do a PR with your project.

**Comment by cmcintosh** [comment]
Its not my Project I dont have the source, which is why Im asking for it from your team, but hey thanks for nothing.  I have moved onto another CRM with better community support.
